<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacy Policy</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #ffffff;
            padding: 16px;
            color: #000;
        }
        h1 {
            font-size: 20px;
            font-weight: bold;
            color: #151546; /* Replace with your app's color theme */
        }
        h2 {
            font-size: 18px;
            font-weight: bold;
            margin: 10px 0;
        }
        p, li {
            font-size: 14px;
            line-height: 1.5;
        }
        .italic {
            font-style: italic;
        }
    </style>
</head>
<body>
    <h1>PRIVACY POLICY FOR THE BRIDGE APP</h1>
    <p class="italic">Effective as of May 2024</p>

    <h2>1. INTRODUCTION</h2>
    <p>
        This Privacy Policy is tailored to inform users ("you" or "your") of The Bridge, encompassing both the app and website, about our practices regarding the collection, use, and disclosure of personal information. Please take the time to carefully review this Privacy Policy to understand how we handle your data. If we request certain information by which you can be identified while using our platform, rest assured that it will only be utilized in accordance with this privacy statement. By utilizing The Bridge Platform, you consent to the terms outlined in this Privacy Policy as well as our Terms of Service. We highly value your privacy and are dedicated to safeguarding your personal information. This Privacy Policy delineates how we gather, utilize, and disclose your data when you engage with The Bridge App.
    </p>

    <h2>2. INTERPRETATIONS AND DEFINITIONS</h2>
    <p>
        The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
    </p>
    <p>
        <strong>Definitions</strong>
    </p>
    <ul>
        <li>“Account” means a unique account created for You to access our Service or parts of our Service;</li>
        <li>“Cookies” are small files that are placed on your computer, mobile device or any other device by a website, containing the details of your browsing history on that website among its many uses;</li>
        <li>“Country” refers to Nigeria;</li>
        <li>“Device” means any device that can access the Service such as a computer, a mobile phone, a digital tablet, etc;</li>
        <li>“Personal Data” is any information that is associated or relates to a specific individual and can be used to identify that person;</li>
        <li>“Service” refers to the mobile applications and all activities as it relates to the Bridge App;</li>
        <li>“Service Provider” means any natural or legal person who processes the data on behalf of the Bridge. It refers to third-party companies or individuals employed by the Bridge to facilitate or provide the Service on behalf of the Bridge, to perform services related to the Service or to assist the Bridge in analyzing how the Service is used;</li>
        <li>“Third-party Social Media Service” refers to any website or any social network website through which a User can log in or create an Account to use the Service;</li>
        <li>“Usage Data” refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself;</li>
        <li>“User“ refers to the individual using this Platform;</li>
        <li>“We”, “Us” or “Our” in this Policy refers to the Bridge Platform; and</li>
        <li>“You“ means the individual accessing or using our Service, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
    </ul>

    <h2>3. INFORMATION WE COLLECT</h2>
    <p>
        We collect the following types of information from users of The Bridge App:
    </p>
    <ul>
        <li>● <strong>Personal Identity Information:</strong> This includes data that can identify you such as your first name, last name, gender, date of birth, username, and similar details as verified by official identification documents such as voter ID cards, NIN cards, International Passport, or driving licenses.</li>
        <li>● <strong>Contact Information:</strong> We collect your mobile number, postal address, email address, and telephone number to facilitate communication and provide services.</li>
        <li>● <strong>Professional Information:</strong> To enhance your job search and help employers find you, we may collect details about your education, work experience, skills, salary, photos, city, and area. Please be cautious not to include personal data in your resume that you do not wish to be publicly available.</li>
        <li>● <strong>Feedback and Correspondence:</strong> If you participate in surveys, market research activities, or report issues with our service, we may collect information you provide during such interactions.</li>
        <li>● <strong>Usage Information:</strong> This encompasses information about how you interact with The Bridge App, including the pages you visit, the features you use, and your activity within the app.</li>
        <li>● <strong>Marketing Information:</strong> Your preferences for receiving marketing communications and details about your engagement with marketing materials.</li>
    </ul>
    <!-- Add more sections as needed -->
</body>
</html>
